# Generated by Django 4.0.4 on 2022-07-15 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque1peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=110)),
                ('quantidade_em_estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estoque_minimo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque4peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=120)),
                ('motorista', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('passageiro', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('assento_esquerdo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('assento_direito', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade_em_estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estoque_minimo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('endereco', models.CharField(max_length=120)),
                ('complemento', models.CharField(max_length=120)),
                ('cep', models.CharField(max_length=12)),
                ('telefone', models.CharField(max_length=12)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('carro', models.CharField(max_length=128)),
                ('ano', models.CharField(max_length=128)),
                ('lado', models.CharField(max_length=128)),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('carro', models.CharField(max_length=128)),
                ('valor_peca', models.CharField(max_length=12)),
                ('obs', models.TextField(blank=True)),
                ('sim', models.BooleanField(default=True, verbose_name='pago')),
                ('nao', models.BooleanField(default=False, verbose_name='Pendente')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pessoa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='vendas',
            field=models.ManyToManyField(through='home.Venda', to='home.pessoa'),
        ),
    ]
